services:
  web_app_dash:
    build: ./web_app_dash
    env_file:
      - ./web_app_dash/.env
    ports:
      - "8050:8050"
    environment:
      - DB_HOST=192.168.1.22
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=27915002
      - DB_NAME=RM
    depends_on:
      - db_workspace1

  web_app_webchip:
    build:
      context: ./web_app_WebChip
      dockerfile: Dockerfile
    env_file:
      - ./web_app_WebChip/.env
    ports:
      - "8087:8087"
    environment:
      - DB_HOST=192.168.1.22
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=27915002
      - DB_NAME=ElEngine
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db_workspace2

  db_workspace1:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 27915002
      POSTGRES_DB: RM
    volumes:
      - pgdata1:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_workspace2:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 27915002
      POSTGRES_DB: ElEngine
    volumes:
      - pgdata2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata1:
  pgdata2: